-- mysql -u user -p < init.sql
CREATE DATABASE IF NOT EXISTS `chef_test`;
CREATE TABLE IF NOT EXISTS `chef_test`.`topics` ( `topic_id` INT NOT NULL AUTO_INCREMENT , `topic_name` VARCHAR(255) NOT NULL , PRIMARY KEY (`topic_id`)) ENGINE = InnoDB;
CREATE USER IF NOT EXISTS 'MYUSER'@'%' IDENTIFIED BY 'MYPASS';GRANT ALL PRIVILEGES ON *.* TO 'MYUSER'@'%' REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
